### ISSUE TITLE
Breakpoints aren't hit

### ISSUE THREAD

**Issue by CherryDT** [s-a/iron-node#101] opened 2016-04-21 12:04 UTC
I've read that I need to add "debugger;", which I did, but it still doesn't break on startup and none of the breakpoints I set are hit either. What can be the reason? (It's an express app without any fancy stuff or frameworks at the moment.)

(Plus, I have no idea what to do with the left pane where it lists part of the package.json and tells me there is no readme.)

**Comment by sedwards2009** [comment] 2016-04-21 20:44
I'm having the same problem with 2.2.17. Going back to 2.2.16, it DOES work as expected.

(OS Kubuntu 15.10, 64bit)

**Comment by BigAB** [comment] 2016-04-22 21:25
Yeah, not sure what happened, but iron-node has become un-usable for me.
Breakpoints don't get hit, you can't step through your code.
The left pane is stuck like it's at a debugger, but clicking continue does nothing.
I don't understand, because even when I go back to earlier versions it stays like this, so maybe something with electron-recompile or something.

It's really sad because I loved iron-node, now I can't get it to work anymore.

**Comment by s-a** [comment] 2016-04-23 05:04
Sorry for this . @sedwards2009  thanks for figuring this out! I think I have time to look at this tomorrow. I d like to open a new issue to discuss and find a way to let the user choose the electron version he wants.  Do you think this would make sense?

**Comment by s-a** [comment] 2016-04-23 05:07
Can some one try the latest electron please?

**Comment by s-a** [comment] 2016-04-25 13:53
Can not reproduce this on Windows. Can someone pls test out latest electron v0.37.7? If this works then ok but other wise we need to roll back to electron v0.37.2.

**Comment by TomOne** [comment] 2016-04-27 17:36
I tested it with Electron v0.37.7, but the issue with ignored breakpoints is still there.

**Comment by s-a** [comment] 2016-04-28 08:09
@TomOne thanks for this!   Can someone test v0.37.2 and send a pull request if this works?

**Comment by zgababa** [comment] 2016-05-08 18:35
Going back to 2.2.15, on OSX 10.11.4 works as expected

**Comment by zgababa** [comment] 2016-05-08 18:44
It works too when I use electron-v0.37.2 with 2.2.17

**Comment by s-a** [comment] 2016-05-12 04:41
This should be fixed in electron gt v0.37.6. I suggest to use electron v1.0.1. Docs to change the version you need can be found at https://github.com/s-a/iron-node/blob/master/docs/CHANGE-ELECTRON-VERSION.md.

**Closed as completed** 2016-05-13 15:46 UTC
Labels: help wanted, need feedback, electron

**Comment by mattkime** [comment] 2016-08-08 21:35
i'm seeing this on 3.0.11. this is the full content of the script thats having the problem - 

```
debugger;
console.log('Hello worrrrrrld!');
```

**Comment by scrawfor** [comment] 2016-08-10 12:34
Same issue for me.  At times one debugger statement will be hit, but then it won't hit any of the others.
