### ISSUE TITLE
iron-node do not work / starts with an error

### ISSUE THREAD

**Issue by weingaunity** [s-a/iron-node#104] opened 2016-05-14 10:06 UTC
i installed with

npm install -g iron-node

and tried a simple file including a "debugger;" statement.

i call it with "iron-node ./test.js" and a dialog-error pops up:

Starting iron-node without further arguments also creates the same error message.
###### 

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: app.getPath is not a function
    at Config (/usr/local/lib/node_modules/iron-node/app/config.js:56:35)
    at initializeApplication (/usr/local/lib/node_modules/iron-node/app/index.js:35:41)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/iron-node/app/index.js:48:15)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
###### 

Do you have any idea how to solve this issue?

My system is Ubuntu 16.04 LTS 64-bit.

Thx.

**Comment by dasilvacontin** [comment] 2016-05-14 10:37
Same here. Maybe related to the electron upgrade.

<img width="532" alt="screenshot 2016-05-14 12 36 03" src="https://cloud.githubusercontent.com/assets/1260830/15267962/a96ac2ca-19d0-11e6-9960-94ad427cf762.png">

**Comment by s-a** [comment] 2016-05-14 12:11
Yes this belongs to electron 1 migration. I use app/config.js in main and in render process. So the app var needs to init differently. Just published 3.0.2. Hope this helps.

**Comment by weingaunity** [comment] 2016-05-14 12:46
No, still the same issue.

I updated to 3.0.2

/usr/local/bin/iron-node -> /usr/local/lib/node_modules/iron-node/bin/run.js
/usr/local/lib
└── iron-node@3.0.2 

In use:
electron-recompile@1.0.16

**Comment by s-a** [comment] 2016-05-14 13:03
Weird it works on windows.  Can you try to debug config.js to see whats going on ?

**Comment by weingaunity** [comment] 2016-05-14 13:49
How to debug? I'm try to find a debug tool and want to try iron-node.....   :-)

Uncaught Exception:
TypeError: app.getPath is not a function
    at Config (/usr/local/lib/node_modules/iron-node/app/config.js:56:35)
    at initializeApplication (/usr/local/lib/node_modules/iron-node/app/index.js:35:41)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/iron-node/app/index.js:48:15)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)

**Comment by s-a** [comment] 2016-05-14 14:54
OK you can install ironNode versions below 3 to make it work. I will setup an Ubuntu machine the next days.

**Comment by s-a** [comment] 2016-05-15 04:59
I cannot reproduce this on Ubuntu 14.04.

can you compare contents of your path `/usr/local/lib/node_modules/iron-node/app/config.js` with https://github.com/s-a/iron-node/blob/b5a4ce02e22aca471fc1a6136de686c3a6811842/app/config.js#L6-L11?

![image](https://cloud.githubusercontent.com/assets/1270662/15272084/2cbb3c52-1a69-11e6-994e-4a9e501a3ce8.png)

**Comment by johanalkstal** [comment] 2016-05-15 08:04
I just installed iron-node on my Windows 10 machine and I'm getting the same error.

![iron-node](https://cloud.githubusercontent.com/assets/1790333/15272798/f0f022f2-1a84-11e6-8ea1-c66d792f7be5.JPG)

**Comment by weingaunity** [comment] 2016-05-15 10:12
/usr/local/lib
└─┬ iron-node@3.0.2 
  └── electron-prebuilt@1.0.2 

I compared both files and they are equal.

Error still exists.

Old Version 2.x works.

**Comment by s-a** [comment] 2016-05-15 12:27
It sounds for me like you have a version mismatch on your machine. Old electron and new ironNode or vice versa. **_Maybe a global installed electron module?**_ Regarding nvm users reported such an error in the past. In fact I got the same error message while migrating to electron 1 but fixed with code changes in config.js.

**Comment by s-a** [comment] 2016-05-16 19:37
I recently installed on 3 different machines. I close this issue unless it is reproducable.

**Comment by okcoker** [comment] 2016-05-17 04:20
This happened for me as as well on OSX 10.11.

Installing `npm install -g iron-node@2.x` worked for me though.

Which is a shame because #98 also applies to me.

**Comment by s-a** [comment] 2016-05-17 07:31
I finaly found a workstation where I have the same issue

**Comment by s-a** [comment] 2016-05-17 07:47
I resolved it with 

``` bash
$ npm uninstall -g iron-node;
unbuild iron-node@3.0.3

$ npm install -g iron-node;
```

**Comment by s-a** [comment] 2016-05-17 08:11
This works only for current terminal session. I think this is NPM related.

``` bash
)npm -v
2.14.20
```

**Comment by s-a** [comment] 2016-05-17 09:43
it could be related to https://github.com/npm/npm/issues/12654

**Comment by okcoker** [comment] 2016-05-17 15:42
Thanks for looking into this @s-a 

I am indeed on newer node/npm

```
npm -v
3.8.6
node -v
v6.1.0
```

**Comment by s-a** [comment] 2016-05-17 17:18
Some one tried to clone and install from repo?

**Comment by enter801** [comment] 2016-05-17 21:33
I cloned and tried to install locally.  Did it with npm link in the iron-node folder, then npm link iron-node in my project folder.  It runs, but still get the error.  Installing pointing to iron-node as a directory, ie. npm install ./iron-node gave the same result.  I'm on OSX 10.11.3.

**Closed as completed** 2016-05-18 07:32 UTC

**Comment by s-a** [comment] 2016-05-18 07:37
i removed the app reference from code. pls check if the global config folder determies correct in v3.0.4 on non windows systems

**Comment by okcoker** [comment] 2016-05-18 07:47
Boom! Seems to work on OSX. Thanks @s-a
